insert into public.categories (slug, name, description, sort_order)
values
  ('ai', 'AI', 'Công cụ AI dành cho học tập và sáng tạo.', 10),
  ('developer-tools', 'Công cụ lập trình', 'IDE, source control và công cụ developer.', 20),
  ('cloud-hosting', 'Cloud & Hosting', 'Cloud credits, hosting và infrastructure.', 30),
  ('productivity', 'Năng suất', 'Ghi chú, quản lý công việc và cộng tác.', 40),
  ('design', 'Thiết kế', 'Thiết kế giao diện, đồ họa và prototyping.', 50),
  ('learning-research', 'Học tập & Nghiên cứu', 'Khóa học, tài liệu và công cụ nghiên cứu.', 60),
  ('security', 'Bảo mật', 'Công cụ bảo mật và quản lý danh tính.', 70),
  ('entertainment', 'Giải trí', 'Ưu đãi giải trí dành cho sinh viên.', 80),
  ('shopping', 'Mua sắm', 'Ưu đãi mua sắm và dịch vụ liên quan.', 90)
on conflict (slug) do update
set
  name = excluded.name,
  description = excluded.description,
  sort_order = excluded.sort_order;

-- Verified from official provider pages on 2026-10-02.
insert into public.offers (
  slug,
  title,
  provider,
  summary,
  description,
  official_url,
  category_id,
  benefit_type,
  benefit_text,
  eligibility,
  how_to_claim,
  audience,
  tags,
  status,
  is_featured,
  last_verified_at,
  published_at
)
values
  (
    'github-student-developer-pack',
    'GitHub Student Developer Pack',
    'GitHub',
    'Gói quyền lợi miễn phí dành cho sinh viên đã xác minh, gồm công cụ developer, cloud và tài nguyên học tập từ GitHub và các đối tác.',
    'GitHub Education tập hợp nhiều ưu đãi dành cho sinh viên trong một Student Developer Pack. Danh sách quyền lợi thay đổi theo thời gian nên người dùng nên kiểm tra trang chính thức trước khi kích hoạt từng offer.',
    'https://education.github.com/pack',
    (select id from public.categories where slug = 'developer-tools'),
    'free',
    'Miễn phí cho sinh viên đã xác minh',
    'Sinh viên từ 13 tuổi trở lên và phải xác minh trạng thái sinh viên. Giáo viên, giảng viên và nhân sự giáo dục không thuộc Student Developer Pack.',
    'Đăng nhập GitHub Education, gửi yêu cầu xác minh sinh viên và truy cập Student Developer Pack sau khi được duyệt.',
    array['student'],
    array['developer-tools', 'education', 'github'],
    'published',
    true,
    '2026-10-02T00:00:00Z',
    '2026-10-02T00:00:00Z'
  ),
  (
    'jetbrains-student-teacher-pack',
    'JetBrains Student & Teacher Pack',
    'JetBrains',
    'Sinh viên và giáo viên đủ điều kiện có thể dùng miễn phí các IDE và .NET tools của JetBrains cho mục đích giáo dục.',
    'Gói giáo dục bao gồm IntelliJ IDEA Ultimate, ReSharper và các IDE/.NET tools khác của JetBrains. License giáo dục không được dùng cho công việc thương mại.',
    'https://sales.jetbrains.com/hc/en-gb/articles/207241195-Do-you-offer-free-educational-licenses-for-students-and-teachers',
    (select id from public.categories where slug = 'developer-tools'),
    'free',
    'Miễn phí IDE & .NET tools',
    'Sinh viên và giảng viên tại cơ sở giáo dục được công nhận. Sinh viên cần theo chương trình học toàn thời gian kéo dài ít nhất một năm.',
    'Đăng ký JetBrains Education và hoàn tất bước xác minh tình trạng sinh viên hoặc giáo viên.',
    array['student', 'teacher'],
    array['ide', 'developer-tools', 'education'],
    'published',
    true,
    '2026-10-02T00:00:00Z',
    '2026-10-02T00:00:00Z'
  ),
  (
    'notion-education-plan',
    'Notion Education Plan',
    'Notion',
    'Education Plan miễn phí cho sinh viên và giáo viên đủ điều kiện, với workspace cá nhân một thành viên và các quyền lợi nâng cao.',
    'Notion cung cấp Education Plan miễn phí cho cá nhân đủ điều kiện, gồm upload không giới hạn và lịch sử chỉnh sửa 30 ngày. Người dùng cần xác minh lại trạng thái giáo dục định kỳ.',
    'https://www.notion.com/help/notion-for-education',
    (select id from public.categories where slug = 'productivity'),
    'free',
    'Education Plan miễn phí',
    'Sinh viên hoặc giáo viên tại trường cao đẳng/đại học được công nhận trong WHED, dùng email của cơ sở giáo dục và workspace một thành viên.',
    'Đăng nhập bằng email trường, đảm bảo đang ở Free Plan và nâng cấp sang Education Plan trong phần cài đặt khi đủ điều kiện.',
    array['student', 'teacher'],
    array['productivity', 'notes', 'education'],
    'published',
    true,
    '2026-10-02T00:00:00Z',
    '2026-10-02T00:00:00Z'
  ),
  (
    'figma-for-education',
    'Figma for Education',
    'Figma',
    'Sinh viên và nhà giáo dục đủ điều kiện có thể nhận quyền truy cập Figma Education miễn phí cho học tập và giảng dạy.',
    'Figma Education cung cấp quyền truy cập miễn phí theo cấp học và loại chương trình. Higher education và một số chương trình đủ điều kiện nhận Professional plan; quyền lợi cụ thể có thể khác theo nhóm người dùng và khu vực.',
    'https://help.figma.com/hc/en-us/articles/360041061214-Figma-for-Education',
    (select id from public.categories where slug = 'design'),
    'free',
    'Education plan miễn phí',
    'Sinh viên hoặc nhà giáo dục đủ điều kiện trong lớp học/chương trình được Figma hỗ trợ, cần email do trường cấp và xác minh education status. Khả dụng theo khu vực.',
    'Tạo tài khoản Figma, mở trang Education và hoàn tất quy trình xác minh trạng thái giáo dục.',
    array['student', 'teacher'],
    array['design', 'prototyping', 'education'],
    'published',
    false,
    '2026-10-02T00:00:00Z',
    '2026-10-02T00:00:00Z'
  ),
  (
    'azure-for-students',
    'Azure for Students',
    'Microsoft Azure',
    'Sinh viên đại học đủ điều kiện nhận $100 Azure credit cùng nhiều dịch vụ miễn phí mà không cần thẻ tín dụng.',
    'Azure for Students cung cấp $100 credit dùng trong 12 tháng, các mức dịch vụ miễn phí theo quota và quyền truy cập catalog Azure trong phạm vi credit. Có thể gia hạn hằng năm khi vẫn còn là sinh viên.',
    'https://azure.microsoft.com/en-us/free/students',
    (select id from public.categories where slug = 'cloud-hosting'),
    'credit',
    '$100 Azure credit',
    'Dành cho sinh viên đại học toàn thời gian đủ điều kiện. Đăng ký bằng email trường; không yêu cầu thẻ tín dụng.',
    'Mở Azure for Students, đăng nhập/xác minh bằng email trường và hoàn tất đăng ký tài khoản sinh viên.',
    array['student'],
    array['cloud', 'azure', 'credit'],
    'published',
    true,
    '2026-10-02T00:00:00Z',
    '2026-10-02T00:00:00Z'
  )
on conflict (slug) do update
set
  title = excluded.title,
  provider = excluded.provider,
  summary = excluded.summary,
  description = excluded.description,
  official_url = excluded.official_url,
  category_id = excluded.category_id,
  benefit_type = excluded.benefit_type,
  benefit_text = excluded.benefit_text,
  eligibility = excluded.eligibility,
  how_to_claim = excluded.how_to_claim,
  audience = excluded.audience,
  tags = excluded.tags,
  status = excluded.status,
  is_featured = excluded.is_featured,
  last_verified_at = excluded.last_verified_at,
  published_at = excluded.published_at;
